config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:{
    registrations:"users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessor :name
  belongs_to :user
  validates :content, :image, presence: true, if: :both_ok?
  mount_uploader :image, ImageUploader

  def both_ok?
   content.blank? && image.blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  def self.find_for_facebook_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    unless user
      user = User.new(
      name: auth.extra.raw_info.name,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
      image_url: auth.info.image,
      password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    unless user
      user = User.new(
      name: auth.info.nickname,
      image_url: auth.info.image,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
      password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  PERMISSIBLE_ATTRIBUTES = %i(name)

  def after_sign_in_path_for(resource)
    pictures_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
    devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
  end
end

app/controllers/pictures_controller.rb
  class PicturesController < ApplicationController
  before_action :set_picture, only:[:edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
   end

   def create
     @picture = Picture.new(pictures_params)
     @picture.user_id = current_user.id
     if @picture.save
       redirect_to pictures_path, notice: "投稿が完了しました！"
     else
       render :new
     end
   end

   def edit
   end

   def update
     if @picture.update(pictures_params)
       redirect_to pictures_path, notice: "投稿を更新しました！"
     else
       render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました！"
  end

  private

    def pictures_params
      params.require(:picture).permit(:content, :image, :image_cache, :remove_image)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @user = User.new
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twiter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource_class
    devise_mapping.to
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
 end
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options ={})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?
        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "instagram", pictures_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" >
        <li><%= link_to "ブログ", pictures_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'マイページ', edit_user_registration_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else%>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

<footer>
  <p>instagramのコピーサイトです</p>
</footer>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: "form-control" %>
  <br>
  <%= f.submit "投稿", class: 'btn btn-primary btn-block' %>
<% end %>
<%= link_to "ブログ一覧画面に戻る", pictures_path %>

app/views/pictures/edit.html.erb
<p id = "notice"><%= notice %></p>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを更新する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
  
    <%= link_to "ブログを作成する", new_picture_path, class: 'btn btn-default' %>
    <h1>ブログ一覧</h1>
    <% @pictures.each do |picture| %>
        <div class="row">
          <p><%= picture.user.name %></p>
          <p><%= image_tag picture.image_url %></p>
          <p><%= picture.content %></p>
          <%= link_to "編集", edit_picture_path(picture), class: 'btn btn-default btn-sm btn-success' %>
          <%= link_to "削除",picture_path(picture), method: :delete, data: {confirm: "本当に削除していいですか？"}, class: 'btn btn-default btn-sm btn-danger' %>
        </div>
    <% end %>

  </div>
</div>

app/views/pictures/new.html.erb
<p id = "notice"><%= notice %></p>
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ブログを作成する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<p class = "flash"><%= notice %><%= alert %></p>
<div class="container mar-top">
  <div class = "box col-md-4 col-sm-8 col-sm-offset-1">
      <img src = "<%= asset_path "instagram.png"%>">
  </div>
  <div class="sign_up col-md-4 col-md-offset-2 col-sm-10">
    <h2>サインアップ</h2>

    <%= form_for(resource, as: resource_name, url: user_registration_path) do |f| %>
      <%= f.error_messages! %>

      <div class="field">
        <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレス" %>
      </div>
      <div class = "field">
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder:"名前" %>
      </div>

      <div class="field">
        <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "パスワード" %>
      </div>

      <div class="field">
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "パスワード（確認）" %>
      </div>

      <div class="actions">
        <%= f.submit "サインアップ", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
    <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
    <% end -%>

    <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
      <% end -%>
    <% end -%>


  </div>
</div>